### ISSUE TITLE
Meteor 1.5(.1) breaks DDP?

### ISSUE THREAD

**Issue by jiku** [jiku/portal#9]
Seems irrespective of `--port x` (3000, 7007)?

```shell
I20170713-17:12:53.407(2)? Internal exception while processing message { msg: 'connect',
I20170713-17:12:53.480(2)?   version: '1',
I20170713-17:12:53.481(2)?   support: [ '1', 'pre2', 'pre1' ] } Cannot read property 'get' of undefined TypeError: Cannot read property 'get' of undefined
I20170713-17:12:53.482(2)?     at withoutInvocation (packages/meteor.js:443:33)
I20170713-17:12:53.482(2)?     at bindAndCatch (packages/meteor.js:452:33)
I20170713-17:12:53.482(2)?     at Object._.extend.setInterval (packages/meteor.js:479:24)
I20170713-17:12:53.483(2)?     at [object Object]._.extend._startHeartbeatIntervalTimer (packages/ddp-common.js:89:44)
I20170713-17:12:53.485(2)?     at [object Object]._.extend.start (packages/ddp-common.js:84:10)
I20170713-17:12:53.485(2)?     at new Session (packages/ddp-server/livedata_server.js:318:20)
I20170713-17:12:53.488(2)?     at [object Object]._.extend._handleConnect (packages/ddp-server/livedata_server.js:1463:29)
I20170713-17:12:53.488(2)?     at packages/ddp-server/livedata_server.js:1379:18

  │   │ └── underscore@1.4.4
```

```shell
meteor --release=1.6-beta.6 --port X
```

works. Unsure which Meteor changes caused/fixed this.

Had to install babel-runtime (in src/, i.e. Meteor app).

# References

http://docs.meteor.com/changelog.html
https://github.com/meteor/meteor/releases

## Related?

https://github.com/meteor/meteor/issues/8727

**Comment by jiku** [comment]
On 1.6.0.1 stable.
